# Generated by Django 4.2.3 on 2023-07-06 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Add product category', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Product name (e.g. Milk)', max_length=20)),
                ('price', models.IntegerField(help_text='Enter price')),
                ('inventory_status', models.CharField(help_text='Is product available or not?', max_length=30)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product_collection')),
            ],
        ),
    ]
