# Generated by Django 4.2.3 on 2023-07-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_collection',
            name='title',
            field=models.CharField(help_text='Add product category', max_length=30, verbose_name='Title'),
        ),
    ]
