# Generated by Django 4.2.3 on 2023-07-06 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_product_collection_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_collection',
            name='title',
            field=models.CharField(help_text='Add product category', max_length=30),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
