# Generated by Django 4.2.3 on 2023-07-08 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_customer_address_line_1_customer_address_line_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='post_code',
        ),
        migrations.AddField(
            model_name='customer',
            name='postcode',
            field=models.CharField(default='', help_text="Enter postcode in the format 'M20 2YH' or 'WX45 3GH'", max_length=8, validators=[django.core.validators.RegexValidator(message="Enter a valid postcode in the format 'M20 2YH' or 'WX45 3GH'", regex='^[A-Z]{1,2}\\d{1,2} ?\\d[A-Z]{2}$')]),
        ),
    ]
