# Generated by Django 4.2.3 on 2023-07-09 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_customer_post_code_customer_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='postcode',
            field=models.CharField(default='', max_length=8, validators=[django.core.validators.RegexValidator(message="Enter a valid postcode in the format 'M20 2YH' or 'WX45 3GH'", regex='^[A-Z]{1,2}\\d{1,2} ?\\d[A-Z]{2}$')]),
        ),
    ]
