# Generated by Django 4.2.3 on 2023-07-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_product_price_currency_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory_status',
            field=models.CharField(choices=[('IN_STOCK', 'In stock'), ('OUT_OF_STOCK', 'Out of stock'), ('LIMITED_STOCK', 'Limited stock'), ('PRE_ORDER', 'Pre-order')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('meat', 'Meat'), ('fish', 'Fish'), ('drinks', 'Drinks'), ('snacks', 'Snacks'), ('frozen', 'Frozen'), ('household', 'Household'), ('other', 'Other')], max_length=100),
        ),
        migrations.DeleteModel(
            name='product_collection',
        ),
    ]
