# Generated by Django 4.2.3 on 2023-07-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_basket_customer_alter_basket_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('meat', 'Meat'), ('fish', 'Fish'), ('drinks', 'Drinks'), ('snacks', 'Snacks'), ('frozen', 'Frozen'), ('household', 'Household'), ('other', 'Other')], max_length=100),
        ),
    ]
