# Generated by Django 4.2.3 on 2023-07-13 15:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('basket', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='myapp.basket')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.product')),
            ],
        ),
    ]
